name: GithubActions-Demo
on:
  push:
    branches: ["main"]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '14' # specify the Node.js version if needed
    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Log into Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: lavakush07/nodeapp-test1
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

